name: Main

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!master'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: |
          cd C:\hostedtoolcache\windows\flutter\1.14.6-beta\x64
          git clean -xdf; git fetch; git checkout -b master v1.15.20
          flutter config --enable-windows-desktop
          cd D:\a\sample_plugin\sample_plugin
      - run: |
          cd example; flutter packages get; flutter build windows -v